### ISSUE TITLE
react-native-matrix-sdk vs matrix-js-sdk which one should I go for?

### ISSUE THREAD

**Issue by abhishektiwari-kiwi** [cuvent/react-native-matrix-sdk#5]
I need to integrate matrix chat in react native where User
1. can send/receive text,image and documents(pdf, doc etc.).
2. can get past messages.
3. can create rooms.
4. can login using accessToken, userId, and homeServer.
5. need to get notifications also.

Are all these features available in this sdk?
Is it okay to use this sdk or should I go for matrix-js-sdk?

Please help me out.

**Comment by hannojg** [comment]
Haven’t used the JS SDK.
I can tell you that the native SDK can handle all the features you have listed.
The JS Sdk is also used to build app.element.io so I guess it should also cover all your use cases.

If you want to see a JS implementation reference check the app Ditto.

However, the JS SDK is probably better documented + currently this SDK is under slicendes that forbids the usage in commercial products, keep this in mind.

**Comment by annie-elequin** [comment]
@abhishektiwari-kiwi  Another option is [rn-matrix](https://rnmatrix.com) (I've been working on it) 

It uses the matrix-js-sdk behind the scenes so it doesn't have the benefits of native stuff like react-native-matrix-sdk, but rn-matrix has an option to work in expo as well as a UI pack with an inbox, message view, and composer. 

(also rn-matrix is basically an abstracted version of Ditto's code)

**Comment by abhishektiwari-kiwi** [comment]
@hannojg and @annie-elequin Thank you so much.

**Comment by abhishektiwari-kiwi** [comment]
@hannojg what do you exactly mean by this?
> this SDK is under a license that forbid the usage in commercial products, keep this in mind.
Can we not use this library in our live project even if take risk of using alpha version?

**Comment by hannojg** [comment]
If the app you are building has a commercial purpose, e.g. generating money in the future, you are not allowed to use this SDK in your application. See the license used for distributing this SDK: https://creativecommons.org/licenses/by-nc-sa/2.0/

Even if your app doesn't generate money right now but has the future purpose to do so, the license forbids the usage in your product.

If your app is free of charge and has no commercial purpose it's okay to use the SDK

**Comment by abhishektiwari-kiwi** [comment]
@hannojg Thank you for your response.
One last question please. just to be fully clear.

Consider the below conditions.
>Our app is free to download.
>Although, We have subscription feature in our app but that is for some other feature unlock. 
>Chat is free totally. Even if in future, we don't plan to make Chat feature paid.

So my question is.
Can we now use this sdk to go live or still it's a no no?
Help me out.

**Comment by hannojg** [comment]
According to your specifications, the app has a commercials aspect in it and using this SDK in your product would violate the license. Sorry, but it is a "no no" 😄 I will update this thread once the license changes.
