### ISSUE TITLE
How can I get rooms list and last messages of each member?

### ISSUE THREAD

**Issue by abhishektiwari-kiwi** [cuvent/react-native-matrix-sdk#6]
I need to show list of members with the name, profile pic and last message I'd begun chat with.
Please suggest.

**Comment by hannojg** [comment]
`getJoinedRooms()` - gets list of rooms the user joined
`getInvitedRooms()` - gets list of rooms the user is invited

Those methods return an array of MXRoomAttributes, which has a `members` property from which you can read user information.
