### ISSUE TITLE
Commercial use license

### ISSUE THREAD

**Issue by ruswerner** [cuvent/react-native-matrix-sdk#9]
Hi @hannojg 

Nice work on this library! I am currently working on a commercial RN project that might be integrating Matrix and found your project. We may be in a position to contribute to this library, however your current CC licensing would prevent us from doing so. Would you be open to changing the license to allow for commercial use if things eventuate?

Cheers

**Comment by annie-elequin** [comment]
@ruswerner Hi! I tried hard to find some sort of email to contact you, but failed, so I'll just respond here - I've also built a RN matrix SDK called **rn-matrix** ([rnmatrix.com](https://rnmatrix.com)) and it uses the Apache 2.0 license. There's a version with native libs and a version for Expo. 

It's basically a wrapper around the matrix-js-sdk, so it's different from react-native-matrix-sdk in that regard (react-native-matrix-sdk is focused on the native mobile code which I conjecture may make it a little more performant than the js) 

if you want to chat, my email is annie@elequin.io and my matrix account is @annie:ditto.chat!

**Comment by ruswerner** [comment]
Hi @annie-elequin ! Thanks for sharing. I'll check out your library and let you know how it goes. I'll also send you an email so you have another way to contact. Cheers

**Comment by menturion** [comment]
@annie-elequin   (cc @ruswerner )

Your last activity in your "old" Ditto mobile (with Apache 2.0 license) repo (https://gitlab.com/ditto-chat/ditto-mobile/activity) is two months ago. 

Reason seems to be that you created a "new" repo of Ditto mobile (https://gitlab.com/ditto-chat/ditto) that, however, uses the General Public License v3.0.

**Comment by annie-elequin** [comment]
@menturion that's all correct! However, Ditto isn't the Matrix SDK, it's actually rn-matrix. Ditto just uses it. (Ditto is just a client I'm working on)  

[https://gitlab.com/annie-elequin/rn-matrix](https://gitlab.com/annie-elequin/rn-matrix)

**Comment by menturion** [comment]
Hi Annie, thanks for clarification.

**Comment by hannojg** [comment]
changed to MIT license
